[project]
name = "smugmugalbumuploadcleaner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black==25.1.0",
    "python-dotenv==1.0.1",
    "rauth==0.7.3",
]
